plugins { id 'com.android.application' }
android {
    namespace 'kr.fdc.mortar'
    compileSdk 34
    defaultConfig {
        applicationId 'kr.fdc.mortar'
        minSdk 24
        targetSdk 34
        versionCode((System.getenv('GITHUB_RUN_NUMBER') ?: '1') as int)
        versionName "0.${System.getenv('GITHUB_RUN_NUMBER') ?: '1'}"
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
